#!/usr/bin/env bash

while read os arch; do
  identifier="philote-$os"-"$arch"
  build_dir="pkg/$identifier"
  mkdir -p "$build_dir"
  echo "Compiling for $os/$arch"

  GOOS=$os GOARCH=$arch go build -o "$build_dir"/philote       &&
    cd pkg && tar -zcvf "$identifier".tar.gz "$identifier"     &&
    cd ..
done << EOF
darwin 386
darwin amd64
darwin arm
darwin arm64
dragonfly amd64
freebsd 386
freebsd amd64
freebsd arm
linux 386
linux amd64
linux arm
linux arm64
linux ppc64
linux ppc64le
linux mips64
linux mips64le
netbsd  386
netbsd  amd64
netbsd  arm
openbsd 386
openbsd amd64
openbsd arm
plan9 386
plan9 amd64
solaris amd64
windows 386
windows amd64
EOF
wait

echo "All Done"
